/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "rnaptupqqiozvljmmntt"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJuYXB0dXBxcWlvenZsam1tbnR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU2NTc1MDIsImV4cCI6MjA4MTIzMzUwMn0.d8Lhgfcqi_3pEqxaDs_UlLxFj7Ncn_ml1Ot-tYZOqn4"
